version: "3"

services:
    pico:
        image: christiannxtlvl/php-server:7.4
        container_name: wiki
        ports:
            - '90:80'
        environment:
            PICO_URL_REWRITING: 1
        volumes: 
            - ./:/var/www/html