version: "3"

services:
    wiki:
        image: christiangroeber/php-server:8.1.2
        container_name: wiki
        ports:
            - '94:80'
        volumes:
            - ./:/var/www/html
        environment:
            SECRET: 'asdf'